### ISSUE TITLE
Missing project files

### ISSUE THREAD

**Issue by Poikilos** [taikedz-mt/nssm#6]
Hi, I see [your comment on the upstream version](https://github.com/NPXcoot/nssm/issues/23#issuecomment-487384125) where you say you are maintaining nssm to some degree. Did you ever get the **blend** files? The upstream version is missing them as well--it says it is LGPL, but b3d files are basically binary blobs :( (morwa_statue.b3d) and x files are xml but not reasonably modifiable (blender 2.4 has an x importer but I didn't get correct nor complete data with it when trying to import other mobs). I could help with the quality if only I could edit the files. X and b3d importers (any I've seen, even standalone converterd like assimp) can only get static mesh data, not animations.

**Comment by taikedz** [comment]
Hi

Yes I'm acting as maintainer for the code at this point in NPX Team's absence. However this was a reaction to the team disappearing so no, I never did get the original model files :-(

**Comment by Poikilos** [comment]
@taikedz I want to let you know I found them! <https://github.com/NPXcoot/Nssm-models-textures-sounds>

**Comment by taikedz** [comment]
Awesome!
